//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace F1toPCO.Model.F1 {

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRoot("attributes")]
    public class attributes {
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "attribute")]
        public List<attribute> attribute { get; set; }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class attribute {

        private string _id = ""; 

        private string _uri = "";

        private string _name = "";

        public attribute() {

        }

        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public string id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }

       [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri")]
        public string uri {
            get {
                return this._uri;
            }
            set {
                this._uri = value;
            }
        }

       [System.Xml.Serialization.XmlElementAttribute(ElementName = "name", IsNullable=false)]
       public string name {
           get {
               return this._name;
           }
           set {
               this._name = value;
           }
       }
    }
}