//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

[System.SerializableAttribute()]
[System.Xml.Serialization.XmlRoot("Communications")]
public class CommunicationsCollection {
    [XmlArray("Communications")]
    [XmlArrayItem("Communication", typeof(communication))]
    public communication[] Person { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class communication {
    
    private household householdField;
    
    private person personField;
    
    private communicationType communicationTypeField;
    
    private communicationGeneralType communicationGeneralTypeField;
    
    private string communicationValueField;
    
    private string searchCommunicationValueField;
    
    private bool listedField;
    
    private string communicationCommentField;
    
    private System.Nullable<System.DateTime> createdDateField;
    
    private System.Nullable<System.DateTime> lastUpdatedDateField;
    
    private string uriField;
    
    private string idField;
    
    public communication() {
        this.createdDateField = new System.DateTime(0);
        this.lastUpdatedDateField = new System.DateTime(0);
    }
    
    /// <remarks/>
    public household household {
        get {
            return this.householdField;
        }
        set {
            this.householdField = value;
        }
    }
    
    /// <remarks/>
    public person person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
    
    /// <remarks/>
    public communicationType communicationType {
        get {
            return this.communicationTypeField;
        }
        set {
            this.communicationTypeField = value;
        }
    }
    
    /// <remarks/>
    public communicationGeneralType communicationGeneralType {
        get {
            return this.communicationGeneralTypeField;
        }
        set {
            this.communicationGeneralTypeField = value;
        }
    }
    
    /// <remarks/>
    public string communicationValue {
        get {
            return this.communicationValueField;
        }
        set {
            this.communicationValueField = value;
        }
    }
    
    /// <remarks/>
    public string searchCommunicationValue {
        get {
            return this.searchCommunicationValueField;
        }
        set {
            this.searchCommunicationValueField = value;
        }
    }
    
    /// <remarks/>
    public bool listed {
        get {
            return this.listedField;
        }
        set {
            this.listedField = value;
        }
    }
    
    /// <remarks/>
    public string communicationComment {
        get {
            return this.communicationCommentField;
        }
        set {
            this.communicationCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> createdDate {
        get {
            return this.createdDateField;
        }
        set {
            this.createdDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> lastUpdatedDate {
        get {
            return this.lastUpdatedDateField;
        }
        set {
            this.lastUpdatedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class communicationType {
    
    private object nameField;
    
    private string uriField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum communicationGeneralType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    Email,
    
    /// <remarks/>
    Telephone,
    
    /// <remarks/>
    SocialMedia,
    
    /// <remarks/>
    Web,
}
