//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace F1toPCO.Model.PCO {

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRoot("people")]
    public class people {
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "person")]
        public List<person> person { get; set; }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class id {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRoot("person")]
    public partial class person : BaseModel {

        public person() {
            this.createdById = new personCreatedById();
            this.createDate = new personCreateDate();
            this.updateDate = new personUpdateDate();
            this.updatedById = new personUpdatedById();
            this.id = new id();
            this.contactData = new contactData();
            this.contactData.addresses = new addresses();
            this.contactData.phoneNumbers = new phoneNumbers();
            this.contactData.emailAddresses = new emailAddresses();
        }

        private string firstnameField;

        private string lastnameField;

        private string nameField;

        private string permissionsField;

        private string photothumbnailurlField;

        private string photourlField;

        private personCreateDate createDateField;

        private personCreatedById createdByIdField;

        private id idField;

        private personUpdateDate updateDateField;

        private personUpdatedById updatedByIdField;

        private contactData contactDataField;

        private properties propertiesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("first-name", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                SetField(ref firstnameField, value, "firstname");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-name", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                SetField(ref lastnameField, value, "lastname");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                SetField(ref nameField, value, "name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string permissions {
            get {
                return this.permissionsField;
            }
            set {
                SetField(ref permissionsField, value, "permissions");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("photo-thumbnail-url", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string photothumbnailurl {
            get {
                return this.photothumbnailurlField;
            }
            set {
                this.photothumbnailurlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("photo-url", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string photourl {
            get {
                return this.photourlField;
            }
            set {
                this.photourlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("created-at", IsNullable = true)]
        public personCreateDate createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("created-by-id", IsNullable = true)]
        public personCreatedById createdById {
            get {
                return this.createdByIdField;
            }
            set {
                this.createdByIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", IsNullable = true)]
        public id id {
            get {
                return this.idField;
            }
            set {
                SetField(ref idField, value, "id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updated-at", IsNullable = true)]
        public personUpdateDate updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updated-by-id", IsNullable = true)]
        public personUpdatedById updatedById {
            get {
                return this.updatedByIdField;
            }
            set {
                SetField(ref updatedByIdField, value, "updatedbyid");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contact-data")]
        public contactData contactData {
            get {
                return this.contactDataField;
            }
            set {
                SetField(ref contactDataField, value, "contactdata");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public properties properties {
            get {
                return this.propertiesField;
            }
            set {
                SetField(ref propertiesField, value, "properties");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class personCreateDate {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class personCreatedById {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class personUpdateDate {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class personUpdatedById {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class contactData : BaseModel {

        private addresses addressesField;

        private emailAddresses emailAddressesField;

        private phoneNumbers phoneNumbersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public addresses addresses {
            get {
                return this.addressesField;
            }
            set {
                SetField(ref addressesField, value, "addresses");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-addresses", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public emailAddresses emailAddresses {
            get {
                return this.emailAddressesField;
            }
            set {
                SetField(ref emailAddressesField, value, "emailaddresses");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-numbers", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public phoneNumbers phoneNumbers {
            get {
                return this.phoneNumbersField;
            }
            set {
                SetField(ref phoneNumbersField, value, "phonenumbers");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class addresses : BaseModel {

        public addresses() {
            this.address = new List<address>();
        }

        private List<address> addressField;

        private string typeField = "array";

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<address> address {
            get {
                return this.addressField;
            }
            set {
                SetField(ref addressField, value, "address");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                SetField(ref typeField, value, "type");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class address : BaseModel {

        private string cityField;

        private string stateField;

        private string streetField;

        private string zipField;

        private string locationField;

        private id[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                SetField(ref cityField, value, "city");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                SetField(ref stateField, value, "state");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                SetField(ref streetField, value, "street");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                SetField(ref zipField, value, "zip");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                SetField(ref locationField, value, "location");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", IsNullable = true)]
        public id[] id {
            get {
                return this.idField;
            }
            set {
                SetField(ref idField, value, "id");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class emailAddresses : BaseModel {

        public emailAddresses() {
            this.emailAddress = new List<emailAddress>();
        }

        private List<emailAddress> emailAddressField;

        private string typeField = "array";

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-address", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<emailAddress> emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                SetField(ref emailAddressField, value, "emailaddress");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                SetField(ref typeField, value, "type");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class emailAddress : BaseModel {

        private string addressField;

        private string locationField;

        private id[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                SetField(ref addressField, value, "address");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                SetField(ref locationField, value, "location");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", IsNullable = true)]
        public id[] id {
            get {
                return this.idField;
            }
            set {
                SetField(ref idField, value, "id");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class phoneNumbers : BaseModel {

        public phoneNumbers() {
            this.phoneNumber = new List<phoneNumber>();
        }

        private List<phoneNumber> phoneNumberField;

        private string typeField = "array";

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-number", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<phoneNumber> phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                SetField(ref phoneNumberField, value, "phonenumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                SetField(ref typeField, value, "type");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class phoneNumber : BaseModel {

        private string numberField;

        private string locationField;

        private id[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                SetField(ref numberField, value, "number");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                SetField(ref locationField, value, "location");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", IsNullable = true)]
        public id[] id {
            get {
                return this.idField;
            }
            set {
                SetField(ref idField, value, "id");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class properties : BaseModel {

        private List<property> propertyField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<property> property {
            get {
                return this.propertyField;
            }
            set {
                SetField(ref propertyField, value, "property");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                SetField(ref typeField, value, "type");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class property : BaseModel {

        private string fieldField;

        private string fieldallowsmultipleselectionsField;

        private string optionField;

        private id[] idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                SetField(ref fieldField, value, "field");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("field-allows-multiple-selections", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fieldallowsmultipleselections {
            get {
                return this.fieldallowsmultipleselectionsField;
            }
            set {
                SetField(ref fieldallowsmultipleselectionsField, value, "fieldallowsmultipleselections");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string option {
            get {
                return this.optionField;
            }
            set {
                SetField(ref optionField, value, "option");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", IsNullable = true)]
        public id[] id {
            get {
                return this.idField;
            }
            set {
                SetField(ref idField, value, "id");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", typeof(id), IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("person", typeof(person))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}