//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace F1toPCO.Model.F1 {

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRoot("results")]
    public class people {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "person")]
        public List<person> items { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "pageNumber")]
        public string page { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "count")]
        public string count { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "totalRecords")]
        public string total { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "additionalPages")]
        public string pages { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class person : BaseModel {

        private string titleField;

        private string salutationField;

        private string prefixField;

        private string firstNameField;

        private string lastNameField;

        private string suffixField;

        private string middleNameField;

        private string goesByNameField;

        private string formerNameField;

        private System.Nullable<gender> genderField;

        private string dateOfBirthField;

        private System.Nullable<maritalStatus> maritalStatusField;

        private householdMemberType householdMemberTypeField;

        private string isAuthorizedField;

        private status statusField;

        private occupation occupationField;

        private string employerField;

        private school schoolField;

        private communications communicationsField;

        private addresses addressesField;

        private peopleAttributes peopleAttributesField;

        private denomination denominationField;

        private string formerChurchField;

        private string barCodeField;

        private string memberEnvelopeCodeField;

        private string defaultTagCommentField;

        private weblink weblinkField;

        private string solicitField;

        private string thankField;

        private string firstRecordField;

        private string lastMatchDateField;

        private string createdDateField;

        private string lastUpdatedDateField;

        private string uriField;

        private string imageURIField;

        private string idField;

        private string oldIDField;

        private string oldHouseholdIDField;

        private string iCodeField;

        private string householdIDField;

        public person() {

        }
       
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "title", IsNullable = true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                SetField(ref titleField, value, "title");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "salutation", IsNullable = true)]
        public string salutation {
            get {
                return this.salutationField;
            }
            set {
                SetField(ref salutationField, value, "salutation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "prefix", IsNullable = true)]
        public string prefix {
            get {
                return this.prefixField;
            }
            set {
                SetField(ref prefixField, value, "prefix");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "firstName", IsNullable = true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                SetField(ref firstNameField, value, "firstName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "lastName", IsNullable = true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                SetField(ref lastNameField, value, "lastName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "suffix", IsNullable = true)]
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                SetField(ref suffixField, value, "suffix");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "middleName", IsNullable = true)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                SetField(ref middleNameField, value, "middleName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "goesByName", IsNullable = true)]
        public string goesByName {
            get {
                return this.goesByNameField;
            }
            set {
                SetField(ref goesByNameField, value, "goesByName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "formerName", IsNullable = true)]
        public string formerName {
            get {
                return this.formerNameField;
            }
            set {
                SetField(ref formerNameField, value, "formerName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "gender", IsNullable = true)]
        public System.Nullable<gender> gender {
            get {
                return this.genderField;
            }
            set {
                SetField(ref genderField, value, "gender");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "dateOfBirth", IsNullable = true)]
        public string dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                SetField(ref dateOfBirthField, value, "dateOfBirth");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "maritalStatus", IsNullable = true)]
        public System.Nullable<maritalStatus> maritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                SetField(ref maritalStatusField, value, "maritalStatus");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "householdMemberType", IsNullable = true)]
        public householdMemberType householdMemberType {
            get {
                return this.householdMemberTypeField;
            }
            set {
                SetField(ref householdMemberTypeField, value, "householdMemberType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "isAuthorized", IsNullable = true)]
        public string isAuthorized {
            get {
                return this.isAuthorizedField;
            }
            set {
                SetField(ref isAuthorizedField, value, "isAuthorized");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "status", IsNullable = true)]
        public status status {
            get {
                return this.statusField;
            }
            set {
                SetField(ref statusField, value, "status");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "occupation", IsNullable = true)]
        public occupation occupation {
            get {
                return this.occupationField;
            }
            set {
                SetField(ref occupationField, value, "occupation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "employer", IsNullable = true)]
        public string employer {
            get {
                return this.employerField;
            }
            set {
                SetField(ref employerField, value, "employer");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "addresses", IsNullable = true)]
        public addresses addresses {
            get {
                return this.addressesField;
            }
            set {
                SetField(ref addressesField, value, "addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "communications", IsNullable = true)]
        public communications communications {
            get {
                return this.communicationsField;
            }
            set {
                SetField(ref communicationsField, value, "communications");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "school", IsNullable = true)]
        public school school {
            get {
                return this.schoolField;
            }
            set {
                SetField(ref schoolField, value, "school");
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(ElementName = "attributes", IsNullable = true)]
        public peopleAttributes attributes {
            get {
                return this.peopleAttributesField;
            }
            set {
                SetField(ref peopleAttributesField, value, "attributes");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "denomination", IsNullable = true)]
        public denomination denomination {
            get {
                return this.denominationField;
            }
            set {
                SetField(ref denominationField, value, "denomination");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "formerChurch", IsNullable = true)]
        public string formerChurch {
            get {
                return this.formerChurchField;
            }
            set {
                SetField(ref formerChurchField, value, "formerChurch");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "barCode", IsNullable = true)]
        public string barCode {
            get {
                return this.barCodeField;
            }
            set {
                SetField(ref barCodeField, value, "barCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "memberEnvelopeCode", IsNullable = true)]
        public string memberEnvelopeCode {
            get {
                return this.memberEnvelopeCodeField;
            }
            set {
                SetField(ref memberEnvelopeCodeField, value, "memberEnvelopeCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "defaultTagComment", IsNullable = true)]
        public string defaultTagComment {
            get {
                return this.defaultTagCommentField;
            }
            set {
                SetField(ref defaultTagCommentField, value, "defaultTagComment");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "webLink", IsNullable = true)]
        public weblink weblink {
            get {
                return this.weblinkField;
            }
            set {
                SetField(ref weblinkField, value, "weblink");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "solicit", IsNullable = true)]
        public string solicit {
            get {
                return this.solicitField;
            }
            set {
                SetField(ref solicitField, value, "solicit");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "thank", IsNullable = true)]
        public string thank {
            get {
                return this.thankField;
            }
            set {
                SetField(ref thankField, value, "thank");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "firstRecord", IsNullable = true)]
        public string firstRecord {
            get {
                return this.firstRecordField;
            }
            set {
                SetField(ref firstRecordField, value, "firstRecord");
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='0001-01-01T00:00:00' attribute.
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "lastMatchDate", IsNullable = true)]
        public string lastMatchDate {
            get {
                return this.lastMatchDateField;
            }
            set {
                SetField(ref lastMatchDateField, value, "lastMatchDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "createdDate", IsNullable = true)]
        public string createdDate {
            get {
                return this.createdDateField;
            }
            set {
                SetField(ref createdDateField, value, "createdDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "lastUpdatedDate", IsNullable = true)]
        public string lastUpdatedDate {
            get {
                return this.lastUpdatedDateField;
            }
            set {
                SetField(ref lastUpdatedDateField, value, "lastUpdatedDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                SetField(ref uriField, value, "uri");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "imageURIField", DataType = "anyURI")]
        public string imageURI {
            get {
                return this.imageURIField;
            }
            set {
                SetField(ref imageURIField, value, "imageURI");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public string id {
            get {
                return this.idField;
            }
            set {
                SetField(ref idField, value, "id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "oldID")]
        public string oldID {
            get {
                return this.oldIDField;
            }
            set {
                SetField(ref oldIDField, value, "oldID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "oldHouseholdID")]
        public string oldHouseholdID {
            get {
                return this.oldHouseholdIDField;
            }
            set {
                SetField(ref oldHouseholdIDField, value, "oldHouseholdID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "iCodeField")]
        public string iCode {
            get {
                return this.iCodeField;
            }
            set {
                SetField(ref iCodeField, value, "iCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "householdID", DataType = "integer")]
        public string householdID {
            get {
                return this.householdIDField;
            }
            set {
                SetField(ref householdIDField, value, "householdID");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public enum gender {

        /// <remarks/>
        Male,

        /// <remarks/>
        Female,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public enum maritalStatus {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Child/Yth")]
        ChildYth,

        /// <remarks/>
        Divorced,

        /// <remarks/>
        Married,

        /// <remarks/>
        Separated,

        /// <remarks/>
        Single,

        /// <remarks/>
        Widow,

        /// <remarks/>
        Widower,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class householdMemberType {

        private System.Nullable<householdMemberTypeName> nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<householdMemberTypeName> name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum householdMemberTypeName {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,

        /// <remarks/>
        Head,

        /// <remarks/>
        Spouse,

        /// <remarks/>
        Child,

        /// <remarks/>
        Other,

        /// <remarks/>
        Visitor,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class status {

        private string nameField;

        private string commentField;

        private string dateField;

        private subStatus subStatusField;

        private string uriField;

        private short idField;

        public status() {
            this.dateField = "0001-01-01T00:00:00";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }

        /// <remarks/>
        public subStatus subStatus {
            get {
                return this.subStatusField;
            }
            set {
                this.subStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class subStatus {

        private string nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class occupation {

        private string nameField;

        private string descriptionField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class school {

        private string nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class denomination {

        private string nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class weblink {

        private string userIDField;

        private string passwordHintField;

        private string passwordAnswerField;

        public weblink() {
            this.userIDField = "";
            this.passwordHintField = "";
            this.passwordAnswerField = "";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string passwordHint {
            get {
                return this.passwordHintField;
            }
            set {
                this.passwordHintField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string passwordAnswer {
            get {
                return this.passwordAnswerField;
            }
            set {
                this.passwordAnswerField = value;
            }
        }
    }
}